/**
 * Shop proxy — forwards card shop requests to the hosted bitpos.app fulfillment API.
 * All shipping details are sent to bitpos.app, which handles fulfillment via printags.
 * The Lightning invoice is generated by bitpos.app's NWC; the self-hosted app pays it.
 *
 * X-BitPOS-Instance header: HMAC-SHA256 signature authenticating this self-hosted instance.
 */
import axios from "axios";
import { createHmac } from "crypto";
import { logger } from "./logger.js";

const SHOP_API_URL = process.env.SHOP_API_URL ?? "https://bitpos.app/api/shop";

// Shared secret for shop proxy authentication.
// Set SHOP_INSTANCE_SECRET in your environment to a stable unique value per deployment.
// Without it a per-process random secret is used — set it for stable signatures across restarts.
if (!process.env.SHOP_INSTANCE_SECRET) {
  console.warn(
    "[bitpos] SHOP_INSTANCE_SECRET is not set — using a per-process random secret. " +
    "Set SHOP_INSTANCE_SECRET to a stable value for consistent shop proxy authentication."
  );
}
import { randomBytes as _rb } from "crypto";
const SHOP_INSTANCE_SECRET =
  process.env.SHOP_INSTANCE_SECRET ?? _rb(32).toString("hex");

const OSS_VERSION = "1.0.0";

function makeInstanceHeader(): string {
  const timestamp = Date.now().toString();
  const sig = createHmac("sha256", SHOP_INSTANCE_SECRET)
    .update(`${timestamp}:${OSS_VERSION}`)
    .digest("hex");
  return `t=${timestamp},v=${sig},version=${OSS_VERSION}`;
}

const PROXY_HEADERS = () => ({
  "X-BitPOS-Instance": makeInstanceHeader(),
  "Content-Type": "application/json",
  "User-Agent": `bitpos-oss/${OSS_VERSION}`,
});

export async function proxyGetDesigns(): Promise<unknown> {
  const resp = await axios.get(`${SHOP_API_URL}/designs`, {
    headers: PROXY_HEADERS(),
    timeout: 10_000,
  });
  return resp.data;
}

export interface QuoteParams {
  country: string;
  quantity: number;
  designId?: string;
}

export async function proxyGetQuote(params: QuoteParams): Promise<unknown> {
  const resp = await axios.get(`${SHOP_API_URL}/quote`, {
    params,
    headers: PROXY_HEADERS(),
    timeout: 10_000,
  });
  return resp.data;
}

export interface CreateOrderParams {
  designId?: string;
  quantity: number;
  shippingName: string;
  shippingEmail: string;
  shippingPhone?: string;
  shippingAddress1: string;
  shippingAddress2?: string;
  shippingCity: string;
  shippingPostalCode: string;
  shippingCountry: string;
}

export interface CreateOrderResult {
  remoteOrderId: string;
  bolt11?: string;
  paymentHash?: string;
  amountSats: number;
  paid: boolean;
  status: string;
}

export async function proxyCreateOrder(params: CreateOrderParams): Promise<CreateOrderResult> {
  const resp = await axios.post(`${SHOP_API_URL}/orders`, params, {
    headers: PROXY_HEADERS(),
    timeout: 15_000,
  });
  const data = resp.data;
  logger.info({ remoteOrderId: data.orderId }, "Shop order created at bitpos.app");
  return {
    remoteOrderId: data.orderId,
    bolt11: data.invoice?.bolt11,
    paymentHash: data.invoice?.paymentHash,
    amountSats: data.invoice?.amountSats ?? data.amountSats ?? 0,
    paid: data.paid ?? false,
    status: data.status ?? "pending",
  };
}

export async function proxyGetOrder(remoteOrderId: string): Promise<unknown> {
  try {
    const resp = await axios.get(`${SHOP_API_URL}/orders/${remoteOrderId}`, {
      headers: PROXY_HEADERS(),
      timeout: 10_000,
    });
    return resp.data;
  } catch (err) {
    logger.warn({ err, remoteOrderId }, "Failed to fetch order status from bitpos.app");
    return null;
  }
}
