/**
 * Card Shop routes - proxy to hosted bitpos.app fulfillment API.
 * The user's shipping details are forwarded to bitpos.app, which handles
 * printing, packaging, and shipping via printags.
 * The Lightning invoice is generated by bitpos.app; this instance pays it.
 */
import { Router, type IRouter } from "express";
import { eq, desc } from "drizzle-orm";
import { db, cardOrdersTable, accountsTable } from "../db/index.js";
import { requireAuth } from "../middleware/auth.js";
import { processPayment } from "../lib/payment.js";
import { proxyGetDesigns, proxyGetQuote, proxyCreateOrder, proxyGetOrder } from "../lib/shopProxy.js";
import { logger } from "../lib/logger.js";

const router: IRouter = Router();

// GET /api/shop/designs
router.get("/shop/designs", requireAuth, async (_req, res): Promise<void> => {
  try {
    const designs = await proxyGetDesigns();
    res.json(designs);
  } catch (err) {
    logger.error({ err }, "Failed to fetch designs from bitpos.app");
    res.status(502).json({ error: "Failed to fetch designs from fulfillment service" });
  }
});

// GET /api/shop/quote
router.get("/shop/quote", requireAuth, async (req, res): Promise<void> => {
  const { country, quantity, designId } = req.query;
  try {
    const quote = await proxyGetQuote({
      country: String(country ?? ""),
      quantity: Number(quantity ?? 1),
      designId: designId ? String(designId) : undefined,
    });
    res.json(quote);
  } catch (err) {
    logger.error({ err }, "Failed to get quote from bitpos.app");
    res.status(502).json({ error: "Failed to get quote from fulfillment service" });
  }
});

// GET /api/shop/orders
router.get("/shop/orders", requireAuth, async (req, res): Promise<void> => {
  const accountId = req.auth!.accountId;
  const orders = await db
    .select()
    .from(cardOrdersTable)
    .where(eq(cardOrdersTable.accountId, accountId))
    .orderBy(desc(cardOrdersTable.createdAt))
    .limit(50);
  res.json(orders);
});

// GET /api/shop/orders/:id
router.get("/shop/orders/:id", requireAuth, async (req, res): Promise<void> => {
  const localOrderId = Array.isArray(req.params.id) ? req.params.id[0] : req.params.id;
  const accountId = req.auth!.accountId;

  const [order] = await db
    .select()
    .from(cardOrdersTable)
    .where(eq(cardOrdersTable.id, localOrderId));

  if (!order || order.accountId !== accountId) {
    res.status(404).json({ error: "Order not found" });
    return;
  }

  // Fetch live status from bitpos.app if we have a remote order ID
  let remoteStatus: unknown = null;
  if (order.remoteOrderId) {
    remoteStatus = await proxyGetOrder(order.remoteOrderId);
  }

  res.json({ ...order, remoteStatus });
});

// POST /api/shop/orders
router.post("/shop/orders", requireAuth, async (req, res): Promise<void> => {
  const accountId = req.auth!.accountId;

  const {
    designId, quantity = 1,
    shippingName, shippingEmail, shippingPhone,
    shippingAddress1, shippingAddress2,
    shippingCity, shippingPostalCode, shippingCountry,
  } = req.body ?? {};

  if (!shippingName || !shippingAddress1 || !shippingCity || !shippingPostalCode || !shippingCountry) {
    res.status(400).json({ error: "Shipping details are required (name, address1, city, postalCode, country)" });
    return;
  }

  // Create order at bitpos.app
  let remoteOrder: Awaited<ReturnType<typeof proxyCreateOrder>>;
  try {
    remoteOrder = await proxyCreateOrder({
      designId, quantity,
      shippingName, shippingEmail: shippingEmail ?? "",
      shippingPhone, shippingAddress1, shippingAddress2,
      shippingCity, shippingPostalCode, shippingCountry,
    });
  } catch (err) {
    logger.error({ err }, "Failed to create order at bitpos.app");
    res.status(502).json({ error: "Failed to create order with fulfillment service" });
    return;
  }

  // Create local order record first
  const [localOrder] = await db.insert(cardOrdersTable).values({
    accountId,
    remoteOrderId: remoteOrder.remoteOrderId,
    designId: designId ?? null,
    status: "awaiting_payment",
    quantity,
    shippingName,
    shippingEmail: shippingEmail ?? null,
    shippingPhone: shippingPhone ?? null,
    shippingAddress1,
    shippingAddress2: shippingAddress2 ?? null,
    shippingCity,
    shippingPostalCode,
    shippingCountry,
    amountSats: remoteOrder.amountSats,
  }).returning();

  // If bitpos.app returned an invoice, pay it now
  if (remoteOrder.bolt11 && remoteOrder.amountSats > 0 && !remoteOrder.paid) {
    try {
      const { paymentHash } = await processPayment(
        accountId,
        remoteOrder.bolt11,
        remoteOrder.amountSats,
        undefined,
        `Card Shop order (${localOrder.id.slice(-8)})`,
      );

      await db.update(cardOrdersTable)
        .set({ status: "confirmed", updatedAt: new Date() })
        .where(eq(cardOrdersTable.id, localOrder.id));

      logger.info({ orderId: localOrder.id, remoteOrderId: remoteOrder.remoteOrderId, amountSats: remoteOrder.amountSats, paymentHash }, "Shop order paid");
      res.status(201).json({ orderId: localOrder.id, status: "confirmed", amountSats: remoteOrder.amountSats });
    } catch (err: unknown) {
      // Payment failed - cancel local order
      await db.update(cardOrdersTable).set({ status: "cancelled", updatedAt: new Date() }).where(eq(cardOrdersTable.id, localOrder.id));
      const msg = err instanceof Error ? err.message : "Payment failed";
      logger.error({ err: msg, orderId: localOrder.id }, "Shop order payment failed");
      res.status(402).json({ error: `Payment failed: ${msg}` });
    }
  } else {
    // Already paid (e.g. test/free order) or no invoice
    await db.update(cardOrdersTable).set({ status: "confirmed", updatedAt: new Date() }).where(eq(cardOrdersTable.id, localOrder.id));
    res.status(201).json({ orderId: localOrder.id, status: "confirmed", amountSats: remoteOrder.amountSats });
  }
});

export default router;
